kramdown:
  input: GFM
  hard_wrap: true
encoding: utf-8
timezone: Europe/Berlin

sass:
  sass_dir: ./_sass
gems:
  - jemoji
exclude:
  - README.md
include:
  - pages
defaults:
  -
    scope:
      path: ""
    values:
      layout: "rhok"
